Telemetry Instrumentation for ERROR Events
Sunbird-Ed/discussions-middleware pull request #45
Opened 2021-03-19 07:39 UTC by kamaleeswary

2021-03-19 08:54 UTC, vinukumar-vs commented on routes/nodebb.js
> +          if (data !== 'Not Found' && (typeof data) !== 'string') {
Duplication of the code, review with @venkat once

2021-03-19 12:57 UTC, VenkatKadiveti approved these changes

2021-03-22 07:20 UTC, vinukumar-vs requested changes

2021-03-22 07:49 UTC, kamaleeswary commented on app.js
> +  // endpoint: telemetryEventConfig.endpoint,
as of now no needed. maybe if we can use it in the future that's why I commented on 
that.

2021-03-22 08:02 UTC, kamaleeswary commented on libs/sb_telemetry_util/telemetryService.js
> +telemetryService.prototype.getTelemetryAPIError = function (data, res, context) {
I have already done the changes in that repo

2021-03-22 08:33 UTC, vinukumar-vs approved these changes

2021-03-22 08:33 UTC, merged