Issue #SB-27440 feat: Call notification service api call on each acti…
Sunbird-Ed/discussions-middleware pull request #75
Opened 2022-01-05 09:34 UTC by kamaleeswary

…on from DF

2022-01-05 12:12 UTC, VenkatKadiveti approved these changes

2022-01-11 10:25 UTC, VenkatKadiveti requested changes

2022-01-11 10:25 UTC, VenkatKadiveti commented on helpers/constant.json
> +                    "id": "payload.userDetails.id",
createdBy object will have the logged in user, use createdBy object

2022-01-11 10:25 UTC, VenkatKadiveti commented on helpers/notification.js
> +        value = true;
why did you add true here

2022-01-11 10:53 UTC, VenkatKadiveti approved these changes

2022-01-12 07:35 UTC, vinukumar-vs requested changes

2022-01-12 07:35 UTC, vinukumar-vs commented on proxy/proxyUtils.js
> +const handleSessionExpiry = (proxyRes, proxyResData, req, res, error, data, triggerNotification = false) => {
You should not require the flag. You should check the constant object for the request URL has notificationObject, if it is present then trigger notification.

2022-01-12 07:35 UTC, vinukumar-vs commented on routes/nodebb.js
> +const triggerNotification = true;
This is not required

2022-01-12 07:35 UTC, vinukumar-vs commented on routes/nodebb.js
> +const triggerNotification = true;
Instead of this, there should be env variable to trun-off notification for all API's
@VenkatKadiveti

2022-01-12 08:37 UTC, merged